/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    ads: Ad;
    platforms: Platform;
    categories: Category;
    subcategories: Subcategory;
    'content-types': ContentType;
    media: Media;
    users: User;
    'frameio-connections': FrameioConnection;
    'mcp-oauth-clients': McpOauthClient;
    'mcp-oauth-grants': McpOauthGrant;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    ads: AdsSelect<false> | AdsSelect<true>;
    platforms: PlatformsSelect<false> | PlatformsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    'content-types': ContentTypesSelect<false> | ContentTypesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'frameio-connections': FrameioConnectionsSelect<false> | FrameioConnectionsSelect<true>;
    'mcp-oauth-clients': McpOauthClientsSelect<false> | McpOauthClientsSelect<true>;
    'mcp-oauth-grants': McpOauthGrantsSelect<false> | McpOauthGrantsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads".
 */
export interface Ad {
  id: number;
  /**
   * Display version of the caption. Remove @handles, #hashtags, emojis.
   */
  thumbnailTitle: string;
  /**
   * Name of the product/brand being promoted. Shown on tooltips.
   */
  name: string;
  slug: string;
  caption?: string | null;
  video: number | Media;
  thumbnail: number | Media;
  /**
   * Was this ad made using inBeat or by inBeat Agency?
   */
  madeWithInbeat?: boolean | null;
  /**
   * Link to the original ad (if not made with inBeat)
   */
  originalUrl?: string | null;
  companyName?: string | null;
  companyWebsiteUrl?: string | null;
  /**
   * Shortened version of link
   */
  companyWebsiteDisplay?: string | null;
  /**
   * e.g. @dr.squatch
   */
  brandHandleName?: string | null;
  /**
   * If the brand has no social link, use Website as fallback
   */
  brandHandleUrl?: string | null;
  soundName?: string | null;
  soundUrl?: string | null;
  profilePicture?: (number | null) | Media;
  /**
   * Creator credits display
   */
  creatorHandle?: string | null;
  creatorProfileUrl?: string | null;
  platform: number | Platform;
  category?: (number | null) | Category;
  subcategories?: (number | Subcategory)[] | null;
  contentTypes?: (number | ContentType)[] | null;
  ratingAudienceGrab?: number | null;
  ratingWatchability?: number | null;
  ratingClarity?: number | null;
  overallScore?: number | null;
  /**
   * A short statement about the strongest metric.
   */
  highlight?: string | null;
  highlightMetric?: ('audience-grab' | 'watchability' | 'ad-clarity') | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms".
 */
export interface Platform {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-types".
 */
export interface ContentType {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frameio-connections".
 */
export interface FrameioConnection {
  id: number;
  user: number | User;
  accessToken?: string | null;
  refreshToken?: string | null;
  expiresAt?: string | null;
  /**
   * Discovered from /v4/accounts when the connection is made.
   */
  accountId?: string | null;
  accountName?: string | null;
  authState?: string | null;
  authStateExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-oauth-clients".
 */
export interface McpOauthClient {
  id: number;
  clientId: string;
  clientName?: string | null;
  redirectUris:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-oauth-grants".
 */
export interface McpOauthGrant {
  id: number;
  user: number | User;
  client: number | McpOauthClient;
  redirectUri: string;
  codeHash?: string | null;
  codeChallenge?: string | null;
  codeExpiresAt?: string | null;
  accessTokenHash?: string | null;
  accessExpiresAt?: string | null;
  refreshTokenHash?: string | null;
  previousRefreshTokenHash?: string | null;
  refreshExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  ads?: {
    /**
     * Allow clients to find ads.
     */
    find?: boolean | null;
    /**
     * Allow clients to update ads.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  platforms?: {
    /**
     * Allow clients to find platforms.
     */
    find?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
  };
  subcategories?: {
    /**
     * Allow clients to find subcategories.
     */
    find?: boolean | null;
  };
  contentTypes?: {
    /**
     * Allow clients to find content-types.
     */
    find?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Browse Frame.io. Called with no arguments it lists every project and its root folder id; called with a folderId it lists that folder's contents. Use it to find the file id of a video before calling importFrameioAd.
     */
    frameioBrowse?: boolean | null;
    /**
     * Show a Frame.io file's metadata and the size of every rendition available for import, flagging which ones fit under the web size limit. Use this to confirm a file is importable before calling importFrameioAd.
     */
    frameioInspectFile?: boolean | null;
    /**
     * Import a Frame.io video as a draft ad. Downloads the web-sized rendition and its poster frame into Media, resolves the taxonomy slugs, and creates the ad unpublished for human review. Returns the admin edit URL.
     */
    importFrameioAd?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'ads';
        value: number | Ad;
      } | null)
    | ({
        relationTo: 'platforms';
        value: number | Platform;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: number | Subcategory;
      } | null)
    | ({
        relationTo: 'content-types';
        value: number | ContentType;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'frameio-connections';
        value: number | FrameioConnection;
      } | null)
    | ({
        relationTo: 'mcp-oauth-clients';
        value: number | McpOauthClient;
      } | null)
    | ({
        relationTo: 'mcp-oauth-grants';
        value: number | McpOauthGrant;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_select".
 */
export interface AdsSelect<T extends boolean = true> {
  thumbnailTitle?: T;
  name?: T;
  slug?: T;
  caption?: T;
  video?: T;
  thumbnail?: T;
  madeWithInbeat?: T;
  originalUrl?: T;
  companyName?: T;
  companyWebsiteUrl?: T;
  companyWebsiteDisplay?: T;
  brandHandleName?: T;
  brandHandleUrl?: T;
  soundName?: T;
  soundUrl?: T;
  profilePicture?: T;
  creatorHandle?: T;
  creatorProfileUrl?: T;
  platform?: T;
  category?: T;
  subcategories?: T;
  contentTypes?: T;
  ratingAudienceGrab?: T;
  ratingWatchability?: T;
  ratingClarity?: T;
  overallScore?: T;
  highlight?: T;
  highlightMetric?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms_select".
 */
export interface PlatformsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-types_select".
 */
export interface ContentTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frameio-connections_select".
 */
export interface FrameioConnectionsSelect<T extends boolean = true> {
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  expiresAt?: T;
  accountId?: T;
  accountName?: T;
  authState?: T;
  authStateExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-oauth-clients_select".
 */
export interface McpOauthClientsSelect<T extends boolean = true> {
  clientId?: T;
  clientName?: T;
  redirectUris?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-oauth-grants_select".
 */
export interface McpOauthGrantsSelect<T extends boolean = true> {
  user?: T;
  client?: T;
  redirectUri?: T;
  codeHash?: T;
  codeChallenge?: T;
  codeExpiresAt?: T;
  accessTokenHash?: T;
  accessExpiresAt?: T;
  refreshTokenHash?: T;
  previousRefreshTokenHash?: T;
  refreshExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  ads?:
    | T
    | {
        find?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  platforms?:
    | T
    | {
        find?: T;
      };
  categories?:
    | T
    | {
        find?: T;
      };
  subcategories?:
    | T
    | {
        find?: T;
      };
  contentTypes?:
    | T
    | {
        find?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        frameioBrowse?: T;
        frameioInspectFile?: T;
        importFrameioAd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}